name: Rodar script de preços

on:
  schedule:
    - cron: '0 10 * * *'  # 07:00 BRT
    - cron: '0 22 * * *'  # 19:00 BRT
  workflow_dispatch:  # permite rodar manualmente também

env:
  ACTIONS_STEP_DEBUG: true  # ativa logs detalhados

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.0'

      - name: Install dependencies
        run: pip install requests fpdf python-dotenv

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_RECEPTOR: ${{ secrets.EMAIL_RECEPTOR }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        run: python steam_sticker_scrapper/precos_stickers.py

      - name: Commit de histórico e PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add steam_sticker_scrapper/historico_stickers.json steam_sticker_scrapper/precos_stickers.pdf
          git commit -m "Atualização automática [skip ci]" || echo "Nada para commitar"
          git push
