name: Rodar script de preços

on:
  schedule:
    - cron: '0 12 * * *'  # 09:00 BRT
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests fpdf python-dotenv
          python -m pip list

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_RECEPTOR: ${{ secrets.EMAIL_RECEPTOR }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        working-directory: ./steam_sticker_scrapper
        run: python precos_stickers.py

      - name: Commit de histórico e PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add steam_sticker_scrapper/utils/historico_stickers.json steam_sticker_scrapper/generated_files/precos_stickers.pdf
          git commit -m "Atualização automática [skip ci]" || echo "Nada para commitar"
          git push
